import 'package:flutter/material.dart';
import 'package:fv_uikit_flutter/fv_uikit_flutter.dart';

import 'examples.dart';
import 'models.dart';

const List<String> publicWidgetNames = [
  'AppText',
  'AppLoadingSpinner',
  'AppSkeleton',
  'AppDivider',
  'AppLabel',
  'AppButton',
  'AppCheckbox',
  'AppDateTimeField',
  'AppDropdown',
  'AppPasswordField',
  'AppOtpField',
  'AppSearchField',
  'AppTextField',
  'AppAlert',
  'AppBottomSheet',
  'AppModal',
  'AppRadio',
  'AppSwitch',
];

LocalizedText _t(String en, String vi) => LocalizedText(en: en, vi: vi);

PropDocEntry _prop(
  String name,
  String type,
  String defaultValue,
  String en,
  String vi, {
  bool required = false,
}) {
  return PropDocEntry(
    name: name,
    type: type,
    required: required,
    defaultValue: defaultValue,
    description: _t(en, vi),
  );
}

final List<ColorTokenEntry> colorTokens = [
  const ColorTokenEntry(name: 'primaryDefault', color: ColorTokens.primaryDefault),
  const ColorTokenEntry(name: 'primaryHover', color: ColorTokens.primaryHover),
  const ColorTokenEntry(name: 'primaryBg', color: ColorTokens.primaryBg),
  const ColorTokenEntry(name: 'successDefault', color: ColorTokens.successDefault),
  const ColorTokenEntry(name: 'successBg', color: ColorTokens.successBg),
  const ColorTokenEntry(name: 'warningDefault', color: ColorTokens.warningDefault),
  const ColorTokenEntry(name: 'warningBg', color: ColorTokens.warningBg),
  const ColorTokenEntry(name: 'dangerDefault', color: ColorTokens.dangerDefault),
  const ColorTokenEntry(name: 'dangerBg', color: ColorTokens.dangerBg),
  const ColorTokenEntry(name: 'textDefault', color: ColorTokens.textDefault),
  const ColorTokenEntry(name: 'textDescription', color: ColorTokens.textDescription),
  const ColorTokenEntry(name: 'borderDefault', color: ColorTokens.borderDefault),
  const ColorTokenEntry(name: 'bgElevated', color: ColorTokens.bgElevated),
  const ColorTokenEntry(name: 'bgLayout', color: ColorTokens.bgLayout),
];

const List<TokenCategory> tokenCategories = [
  TokenCategory(
    title: LocalizedText(en: 'Spacing', vi: 'Spacing'),
    description: LocalizedText(
      en: 'Insets and gaps used across layout, cards, lists, and forms.',
      vi: 'Khoảng inset và gap được dùng xuyên suốt layout, card, list và form.',
    ),
    quickUse: 'SpacingTokens.paddingM',
    items: [
      TokenValueEntry(name: 'insetDense', value: '8'),
      TokenValueEntry(name: 'insetDefault', value: '12'),
      TokenValueEntry(name: 'insetRelaxed', value: '16'),
      TokenValueEntry(name: 'spaceXS', value: '4'),
      TokenValueEntry(name: 'spaceS', value: '8'),
      TokenValueEntry(name: 'spaceM', value: '12'),
      TokenValueEntry(name: 'spaceL', value: '16'),
      TokenValueEntry(name: 'spaceXL', value: '24'),
      TokenValueEntry(name: 'space2XL', value: '32'),
      TokenValueEntry(name: 'gapS', value: '8'),
      TokenValueEntry(name: 'gapM', value: '12'),
      TokenValueEntry(name: 'gapL', value: '16'),
      TokenValueEntry(name: 'gapXL', value: '24'),
    ],
  ),
  TokenCategory(
    title: LocalizedText(en: 'Radius', vi: 'Radius'),
    description: LocalizedText(
      en: 'Rounded corner values for buttons, panels, fields, and overlays.',
      vi: 'Giá trị bo góc cho button, panel, field và overlay.',
    ),
    quickUse: 'RadiusTokens.radiusL',
    items: [
      TokenValueEntry(name: 'radiusXS', value: '2'),
      TokenValueEntry(name: 'radiusS', value: '4'),
      TokenValueEntry(name: 'radiusM', value: '6'),
      TokenValueEntry(name: 'radiusL', value: '8'),
      TokenValueEntry(name: 'radiusXL', value: '10'),
    ],
  ),
  TokenCategory(
    title: LocalizedText(en: 'Typography', vi: 'Typography'),
    description: LocalizedText(
      en: 'Shared text scale for body copy, labels, and headings.',
      vi: 'Thang chữ dùng chung cho body, label và heading.',
    ),
    quickUse: 'AppText(text: "Title", size: AppTextSize.heading4Bold)',
    items: [
      TokenValueEntry(name: 'bodyXS', value: '12 / 16'),
      TokenValueEntry(name: 'bodyS', value: '14 / 20'),
      TokenValueEntry(name: 'bodyM', value: '16 / 22'),
      TokenValueEntry(name: 'bodyL', value: '18 / 24'),
      TokenValueEntry(name: 'bodyXL', value: '20 / 28'),
      TokenValueEntry(name: 'heading4', value: '24 / 30'),
      TokenValueEntry(name: 'heading3', value: '36 / 44'),
      TokenValueEntry(name: 'heading2', value: '48 / 54'),
      TokenValueEntry(name: 'heading1', value: '64 / 76'),
    ],
  ),
  TokenCategory(
    title: LocalizedText(en: 'Component and icon sizes', vi: 'Kích thước component và icon'),
    description: LocalizedText(
      en: 'Stable size tokens for controls, icons, and layout rhythm.',
      vi: 'Token kích thước ổn định cho control, icon và nhịp layout.',
    ),
    quickUse: 'ComponentSizeTokens.componentM',
    items: [
      TokenValueEntry(name: 'componentXs', value: '16'),
      TokenValueEntry(name: 'componentSm', value: '24'),
      TokenValueEntry(name: 'componentM', value: '32'),
      TokenValueEntry(name: 'componentL', value: '40'),
      TokenValueEntry(name: 'componentXl', value: '48'),
      TokenValueEntry(name: 'iconSizeS', value: '16'),
      TokenValueEntry(name: 'iconSizeM', value: '20'),
      TokenValueEntry(name: 'iconSizeL', value: '24'),
      TokenValueEntry(name: 'iconSizeXL', value: '28'),
    ],
  ),
  TokenCategory(
    title: LocalizedText(en: 'Elevation, breakpoints, z-index', vi: 'Elevation, breakpoints, z-index'),
    description: LocalizedText(
      en: 'Use these values for responsive layout and surface layering.',
      vi: 'Dùng các giá trị này cho responsive layout và phân lớp surface.',
    ),
    quickUse: 'BoxShadowTokens.boxShadowTertiary',
    items: [
      TokenValueEntry(name: 'boxShadow', value: 'primary elevation list'),
      TokenValueEntry(name: 'boxShadowTertiary', value: 'subtle panel shadow'),
      TokenValueEntry(name: 'screenXs', value: '390'),
      TokenValueEntry(name: 'screenMd', value: '740'),
      TokenValueEntry(name: 'screenXl', value: '1280'),
      TokenValueEntry(name: 'zIndexModal', value: '2'),
      TokenValueEntry(name: 'zIndexTooltip', value: '3'),
    ],
  ),
];

final List<NavGroup> navGroups = [
  NavGroup(
    title: _t('Foundations', 'Nền tảng'),
    description: _t(
      'Design tokens and primitive building blocks used by every widget.',
      'Design token và các khối nguyên thủy được dùng bởi mọi widget.',
    ),
    items: [
      NavItem(
        route: '/tokens',
        icon: Icons.palette_outlined,
        title: _t('Tokens', 'Tokens'),
        description: _t(
          'Colors, spacing, radius, typography, sizes, shadows, breakpoints.',
          'Color, spacing, radius, typography, size, shadow, breakpoint.',
        ),
      ),
      NavItem(
        route: '/widgets/app-text',
        icon: Icons.text_fields,
        title: _t('AppText', 'AppText'),
        description: _t('Typography atom with shared text styles.', 'Atom hiển thị chữ với hệ text style dùng chung.'),
      ),
      NavItem(
        route: '/widgets/app-divider',
        icon: Icons.horizontal_rule,
        title: _t('AppDivider', 'AppDivider'),
        description: _t('Horizontal and vertical separators.', 'Đường phân tách ngang và dọc.'),
      ),
      NavItem(
        route: '/widgets/app-label',
        icon: Icons.label_outline,
        title: _t('AppLabel', 'AppLabel'),
        description: _t('Form labels with required and info states.', 'Label form với required và info state.'),
      ),
      NavItem(
        route: '/widgets/app-loading-spinner',
        icon: Icons.autorenew,
        title: _t('AppLoadingSpinner', 'AppLoadingSpinner'),
        description: _t('Reusable spinner for async feedback.', 'Spinner tái sử dụng cho phản hồi async.'),
      ),
      NavItem(
        route: '/widgets/app-skeleton',
        icon: Icons.view_agenda_outlined,
        title: _t('AppSkeleton', 'AppSkeleton'),
        description: _t('Shimmer placeholders for loading layouts.', 'Placeholder shimmer cho layout loading.'),
      ),
    ],
  ),
  NavGroup(
    title: _t('Inputs', 'Nhập liệu'),
    description: _t(
      'Form controls and action widgets used to collect or confirm user input.',
      'Các control form và action widget để thu thập hoặc xác nhận dữ liệu đầu vào.',
    ),
    items: [
      NavItem(
        route: '/widgets/app-button',
        icon: Icons.smart_button_outlined,
        title: _t('AppButton', 'AppButton'),
        description: _t('Variants, sizes, icons, loading, and full width actions.', 'Variant, size, icon, loading và action full width.'),
      ),
      NavItem(
        route: '/widgets/app-text-field',
        icon: Icons.input,
        title: _t('AppTextField', 'AppTextField'),
        description: _t('Generic text entry with validation and slots.', 'Input text tổng quát với validate và slot.'),
      ),
      NavItem(
        route: '/widgets/app-password-field',
        icon: Icons.lock_outline,
        title: _t('AppPasswordField', 'AppPasswordField'),
        description: _t('Password-specific field with visibility toggle.', 'Field mật khẩu với nút ẩn hiện.'),
      ),
      NavItem(
        route: '/widgets/app-search-field',
        icon: Icons.search,
        title: _t('AppSearchField', 'AppSearchField'),
        description: _t('Search input with debounced callback.', 'Ô tìm kiếm với callback debounce.'),
      ),
      NavItem(
        route: '/widgets/app-otp-field',
        icon: Icons.password_outlined,
        title: _t('AppOtpField', 'AppOtpField'),
        description: _t('Separated OTP cells with sanitize and paste support.', 'Các ô OTP tách biệt, có sanitize và hỗ trợ paste.'),
      ),
      NavItem(
        route: '/widgets/app-date-time-field',
        icon: Icons.event_outlined,
        title: _t('AppDateTimeField', 'AppDateTimeField'),
        description: _t('Date, time, and date-time pickers.', 'Picker ngày, giờ và ngày-giờ.'),
      ),
      NavItem(
        route: '/widgets/app-dropdown',
        icon: Icons.arrow_drop_down_circle_outlined,
        title: _t('AppDropdown', 'AppDropdown'),
        description: _t('Selectable lists with search and async states.', 'Danh sách chọn với search và trạng thái async.'),
      ),
      NavItem(
        route: '/widgets/app-checkbox',
        icon: Icons.check_box_outlined,
        title: _t('AppCheckbox', 'AppCheckbox'),
        description: _t('Binary, tristate, boxed, and selectbox selection.', 'Lựa chọn binary, tristate, boxed và selectbox.'),
      ),
      NavItem(
        route: '/widgets/app-radio',
        icon: Icons.radio_button_checked,
        title: _t('AppRadio', 'AppRadio'),
        description: _t('Single-choice grouped selection.', 'Lựa chọn một giá trị trong nhóm.'),
      ),
      NavItem(
        route: '/widgets/app-switch',
        icon: Icons.toggle_on_outlined,
        title: _t('AppSwitch', 'AppSwitch'),
        description: _t('Immediate on and off preferences.', 'Tùy chọn bật tắt có hiệu lực ngay.'),
      ),
    ],
  ),
  NavGroup(
    title: _t('Feedback & Overlays', 'Phản hồi & Overlay'),
    description: _t(
      'Transient surfaces for status, confirmation, and contextual tasks.',
      'Các surface tạm thời cho trạng thái, xác nhận và tác vụ theo ngữ cảnh.',
    ),
    items: [
      NavItem(
        route: '/widgets/app-alert',
        icon: Icons.info_outline,
        title: _t('AppAlert', 'AppAlert'),
        description: _t('Inline and overlay alerts with auto close support.', 'Alert inline và overlay, có hỗ trợ tự đóng.'),
      ),
      NavItem(
        route: '/widgets/app-bottom-sheet',
        icon: Icons.vertical_align_bottom,
        title: _t('AppBottomSheet', 'AppBottomSheet'),
        description: _t('Contextual sheets for small tasks and forms.', 'Bottom sheet cho tác vụ ngắn và form nhỏ.'),
      ),
      NavItem(
        route: '/widgets/app-modal',
        icon: Icons.open_in_new,
        title: _t('AppModal', 'AppModal'),
        description: _t('Focused confirmation and decision dialogs.', 'Modal xác nhận và quyết định có trọng tâm.'),
      ),
    ],
  ),
];

final Map<String, WidgetDocEntry> widgetDocsBySlug = {
  'app-text': WidgetDocEntry(
    slug: 'app-text',
    widgetName: 'AppText',
    title: _t('AppText', 'AppText'),
    summary: _t(
      'Use AppText instead of raw Text when you want typography tokens, shared semantic sizes, and a predictable text API.',
      'Dùng AppText thay cho Text thường khi cần typography token, semantic size dùng chung và API text ổn định.',
    ),
    quickStart: _t(
      "AppText(\n  text: 'Product name',\n  size: AppTextSize.bodyMBold,\n  color: ColorTokens.textDefault,\n)",
      "AppText(\n  text: 'Tên sản phẩm',\n  size: AppTextSize.bodyMBold,\n  color: ColorTokens.textDefault,\n)",
    ),
    props: [
      _prop('text', 'String', '-', 'Text content.', 'Nội dung văn bản.', required: true),
      _prop('style', 'TextStyle?', '-', 'Merged on top of the token style.', 'Được merge lên trên token style.'),
      _prop('textAlign', 'TextAlign?', '-', 'Horizontal text alignment.', 'Căn lề ngang của văn bản.'),
      _prop('maxLines', 'int?', '-', 'Limits the number of rendered lines.', 'Giới hạn số dòng hiển thị.'),
      _prop('overflow', 'TextOverflow?', '-', 'Controls clipping, ellipsis, or fade.', 'Điều khiển cách xử lý tràn nội dung.'),
      _prop('strutStyle', 'StrutStyle?', '-', 'Advanced line-height constraints.', 'Ràng buộc nâng cao cho chiều cao dòng.'),
      _prop('textDirection', 'TextDirection?', '-', 'Overrides ambient text direction.', 'Ghi đè hướng văn bản theo context.'),
      _prop('locale', 'Locale?', '-', 'Locale override for shaping and glyphs.', 'Ghi đè locale để shaping và hiển thị glyph.'),
      _prop('softWrap', 'bool?', '-', 'Allows soft wrapping when width is constrained.', 'Cho phép xuống dòng mềm khi bị giới hạn chiều rộng.'),
      _prop('height', 'double?', '-', 'Overrides line height in the final style.', 'Ghi đè line height trong style cuối.'),
      _prop('color', 'Color?', '-', 'Overrides the final text color.', 'Ghi đè màu chữ cuối cùng.'),
      _prop('fontSize', 'double?', '-', 'Overrides font size after token resolution.', 'Ghi đè font size sau khi resolve token.'),
      _prop('fontWeight', 'AppTextFontWeight?', '-', 'Declared in the API but not currently applied in build.', 'Có trong API nhưng hiện chưa được áp dụng trong build.'),
      _prop('fontStyle', 'FontStyle?', '-', 'Applies italic or normal font style.', 'Áp dụng italic hoặc normal.'),
      _prop('letterSpacing', 'double?', '-', 'Extra spacing between characters.', 'Khoảng cách thêm giữa các ký tự.'),
      _prop('wordSpacing', 'double?', '-', 'Extra spacing between words.', 'Khoảng cách thêm giữa các từ.'),
      _prop('size', 'AppTextSize?', 'bodyMRegular', 'Tokenized text scale variant.', 'Biến thể kích thước chữ theo token.'),
    ],
    examples: buildTextExamples(),
  ),
  'app-loading-spinner': WidgetDocEntry(
    slug: 'app-loading-spinner',
    widgetName: 'AppLoadingSpinner',
    title: _t('AppLoadingSpinner', 'AppLoadingSpinner'),
    summary: _t(
      'Use AppLoadingSpinner when you need active progress feedback instead of a passive placeholder.',
      'Dùng AppLoadingSpinner khi cần phản hồi loading chủ động thay vì placeholder thụ động.',
    ),
    quickStart: _t(
      "const AppLoadingSpinner(\n  size: IconSizeTokens.iconSizeL,\n  color: ColorTokens.primaryDefault,\n)",
      "const AppLoadingSpinner(\n  size: IconSizeTokens.iconSizeL,\n  color: ColorTokens.primaryDefault,\n)",
    ),
    props: [
      _prop('size', 'double', 'IconSizeTokens.iconSizeL', 'Square dimension of the spinner.', 'Kích thước vuông của spinner.'),
      _prop('strokeWidth', 'double', '2', 'Thickness of the progress stroke.', 'Độ dày của nét progress.'),
      _prop('color', 'Color?', 'ColorTokens.primaryDefault', 'Foreground spinner color.', 'Màu hiển thị của spinner.'),
      _prop('backgroundColor', 'Color?', '-', 'Optional track color behind the progress arc.', 'Màu track tùy chọn phía sau vòng progress.'),
      _prop('value', 'double?', '-', 'Determinate progress value from 0 to 1.', 'Giá trị tiến trình xác định từ 0 đến 1.'),
      _prop('padding', 'EdgeInsetsGeometry', 'EdgeInsets.zero', 'Outer spacing without adding a wrapper.', 'Khoảng cách ngoài mà không cần widget bọc thêm.'),
      _prop('semanticsLabel', 'String?', '-', 'Accessibility label for assistive technologies.', 'Nhãn trợ năng cho công cụ hỗ trợ.'),
      _prop('semanticsValue', 'String?', '-', 'Accessibility value for determinate progress.', 'Giá trị trợ năng cho tiến trình xác định.'),
    ],
    examples: buildLoadingExamples(),
  ),
  'app-skeleton': WidgetDocEntry(
    slug: 'app-skeleton',
    widgetName: 'AppSkeleton',
    title: _t('AppSkeleton', 'AppSkeleton'),
    summary: _t(
      'Use AppSkeleton to keep layout structure visible while real data is still loading.',
      'Dùng AppSkeleton để giữ cấu trúc layout trong khi dữ liệu thật còn đang tải.',
    ),
    quickStart: _t(
      "const AppSkeleton(width: 160, height: 20)",
      "const AppSkeleton(width: 160, height: 20)",
    ),
    props: [
      _prop('width', 'double?', '-', 'Optional width for the placeholder.', 'Chiều rộng tùy chọn của placeholder.'),
      _prop('height', 'double?', '16', 'Height of the skeleton surface.', 'Chiều cao của skeleton.'),
      _prop('shape', 'BoxShape', 'BoxShape.rectangle', 'Rectangle or circle skeleton shape.', 'Hình chữ nhật hoặc hình tròn.'),
      _prop('borderRadius', 'BorderRadiusGeometry?', 'RadiusTokens.radiusL', 'Border radius used for rectangle mode.', 'Bo góc dùng cho chế độ hình chữ nhật.'),
      _prop('baseColor', 'Color?', 'ColorTokens.borderSecondary', 'Base shimmer color.', 'Màu nền chính của shimmer.'),
      _prop('highlightColor', 'Color?', 'ColorTokens.bgWarm', 'Moving highlight color.', 'Màu highlight chuyển động.'),
      _prop('duration', 'Duration', '1200ms', 'Loop duration for the shimmer animation.', 'Thời lượng lặp của animation shimmer.'),
      _prop('isAnimated', 'bool', 'true', 'Disables shimmer and renders a static block when false.', 'Tắt shimmer và render khối tĩnh khi false.'),
    ],
    examples: buildSkeletonExamples(),
  ),
  'app-divider': WidgetDocEntry(
    slug: 'app-divider',
    widgetName: 'AppDivider',
    title: _t('AppDivider', 'AppDivider'),
    summary: _t(
      'Use AppDivider to separate related content areas using semantic colors or explicit dimensions.',
      'Dùng AppDivider để tách các vùng nội dung liên quan bằng màu semantic hoặc kích thước cụ thể.',
    ),
    quickStart: _t(
      "const AppDivider(variant: AppDividerVariant.info, thickness: 2)",
      "const AppDivider(variant: AppDividerVariant.info, thickness: 2)",
    ),
    props: [
      _prop('orientation', 'AppDividerOrientation?', 'horizontal', 'Horizontal or vertical divider mode.', 'Chế độ divider ngang hoặc dọc.'),
      _prop('variant', 'AppDividerVariant?', 'defaultValue', 'Semantic color variant for the divider.', 'Biến thể màu semantic của divider.'),
      _prop('color', 'Color?', '-', 'Explicit color override for the divider.', 'Ghi đè màu cụ thể cho divider.'),
      _prop('thickness', 'double?', '2.0', 'Thickness of the line.', 'Độ dày của đường kẻ.'),
      _prop('length', 'double?', '-', 'Width for horizontal or height for vertical mode.', 'Chiều rộng khi ngang hoặc chiều cao khi dọc.'),
      _prop('indent', 'double?', '-', 'Leading inset before the divider line.', 'Khoảng lùi đầu trước đường divider.'),
      _prop('endIndent', 'double?', '-', 'Trailing inset after the divider line.', 'Khoảng lùi cuối sau đường divider.'),
    ],
    examples: buildDividerExamples(),
  ),
  'app-label': WidgetDocEntry(
    slug: 'app-label',
    widgetName: 'AppLabel',
    title: _t('AppLabel', 'AppLabel'),
    summary: _t(
      'Use AppLabel for form captions that need required marks, optional hints, and supporting info affordances.',
      'Dùng AppLabel cho caption của form khi cần dấu bắt buộc, gợi ý optional và affordance thông tin hỗ trợ.',
    ),
    quickStart: _t(
      "const AppLabel(\n  text: 'Email',\n  isRequired: true,\n  showInfoIcon: true,\n  tooltipMessage: 'Used for invoice notifications',\n)",
      "const AppLabel(\n  text: 'Email',\n  isRequired: true,\n  showInfoIcon: true,\n  tooltipMessage: 'Dùng để nhận thông báo hóa đơn',\n)",
    ),
    props: [
      _prop('text', 'String', '-', 'Main label text.', 'Nội dung label chính.', required: true),
      _prop('size', 'AppLabelSize?', 'medium', 'Controls typography and icon metrics.', 'Điều khiển typography và kích thước icon.'),
      _prop('isRequired', 'bool?', 'false', 'Shows required asterisk(s).', 'Hiển thị dấu sao bắt buộc.'),
      _prop('requiredPosition', 'AppLabelRequiredPosition?', 'trailing', 'Places the required mark before, after, or both.', 'Đặt dấu bắt buộc ở trước, sau hoặc cả hai.'),
      _prop('isOptional', 'bool?', 'false', 'Appends optional helper text.', 'Thêm text optional phía sau label.'),
      _prop('optionalText', 'String?', '(optional)', 'Overrides the optional caption text.', 'Ghi đè nội dung optional caption.'),
      _prop('showInfoIcon', 'bool?', 'false', 'Displays the trailing info icon slot.', 'Hiển thị icon info ở cuối.'),
      _prop('infoIcon', 'Widget?', 'Icons.info_outline', 'Custom info icon widget.', 'Widget icon info tùy biến.'),
      _prop('onInfoTap', 'VoidCallback?', '-', 'Callback when the info icon is tapped.', 'Callback khi chạm vào icon info.'),
      _prop('tooltipMessage', 'String?', '-', 'Tooltip content for hover or long press.', 'Nội dung tooltip khi hover hoặc nhấn giữ.'),
      _prop('textColor', 'Color?', 'ColorTokens.textDefault', 'Color of the main label text.', 'Màu của text label chính.'),
      _prop('optionalColor', 'Color?', 'ColorTokens.textDescription', 'Color of the optional text.', 'Màu của phần optional.'),
      _prop('requiredColor', 'Color?', 'ColorTokens.dangerDefault', 'Color of the required asterisk.', 'Màu của dấu sao bắt buộc.'),
      _prop('iconColor', 'Color?', 'ColorTokens.iconDefault', 'Color applied to the info icon.', 'Màu áp dụng cho icon info.'),
      _prop('textStyle', 'TextStyle?', '-', 'Custom style merged into the label text.', 'Style tùy biến merge vào label text.'),
      _prop('optionalStyle', 'TextStyle?', '-', 'Custom style merged into the optional text.', 'Style tùy biến merge vào optional text.'),
      _prop('spacing', 'double?', 'size metric', 'Gap between label content and info icon.', 'Khoảng cách giữa label và icon info.'),
    ],
    examples: buildLabelExamples(),
  ),
  'app-button': WidgetDocEntry(
    slug: 'app-button',
    widgetName: 'AppButton',
    title: _t('AppButton', 'AppButton'),
    summary: _t(
      'Use AppButton for primary and secondary actions with consistent sizing, variants, icon slots, and async states.',
      'Dùng AppButton cho primary và secondary action với size, variant, slot icon và async state nhất quán.',
    ),
    quickStart: _t(
      "AppButton(\n  text: 'Save',\n  variant: AppButtonVariant.primary,\n  onPressed: () {},\n)",
      "AppButton(\n  text: 'Lưu',\n  variant: AppButtonVariant.primary,\n  onPressed: () {},\n)",
    ),
    props: [
      _prop('variant', 'AppButtonVariant?', 'fallback', 'Visual button variant such as primary, outline, link, or danger.', 'Biến thể hiển thị như primary, outline, link hoặc danger.'),
      _prop('size', 'AppButtonSize?', 'medium', 'Controls height, padding, and icon scale.', 'Điều khiển chiều cao, padding và tỷ lệ icon.'),
      _prop('text', 'String', '-', 'Button label.', 'Nhãn của nút.', required: true),
      _prop('onPressed', 'VoidCallback?', '-', 'Tap callback for the button action.', 'Callback khi nhấn nút.'),
      _prop('style', 'ButtonStyle?', '-', 'Merged with the built-in tokenized style.', 'Được merge với style token mặc định.'),
      _prop('textStyle', 'TextStyle?', '-', 'Overrides or extends the label style.', 'Ghi đè hoặc mở rộng style của label.'),
      _prop('textFontSize', 'double?', '-', 'Explicit label font size override.', 'Ghi đè trực tiếp font size của label.'),
      _prop('textColor', 'Color?', '-', 'Explicit label color override.', 'Ghi đè trực tiếp màu label.'),
      _prop('iconLeft', 'Widget?', '-', 'Leading icon widget.', 'Widget icon bên trái.'),
      _prop('iconRight', 'Widget?', '-', 'Trailing icon widget.', 'Widget icon bên phải.'),
      _prop('backgroundColor', 'Color?', 'variant default', 'Explicit background color override.', 'Ghi đè màu nền cụ thể.'),
      _prop('borderColor', 'Color?', 'variant default', 'Explicit border color override.', 'Ghi đè màu viền cụ thể.'),
      _prop('spacing', 'double?', 'size metric', 'Gap between icons and label.', 'Khoảng cách giữa icon và label.'),
      _prop('isFullWidth', 'bool?', 'false', 'Expands to the available width.', 'Mở rộng theo chiều ngang khả dụng.'),
      _prop('isLoading', 'bool?', 'false', 'Disables interaction and shows loading state.', 'Tắt tương tác và hiển thị trạng thái loading.'),
      _prop('isDisabled', 'bool?', 'false', 'Marks the button as disabled.', 'Đánh dấu nút là disabled.'),
      _prop('alignment', 'Alignment?', '-', 'Wrap alignment used for the button content.', 'Căn chỉnh dùng cho nội dung của nút.'),
    ],
    examples: buildButtonExamples(),
  ),
  'app-checkbox': WidgetDocEntry(
    slug: 'app-checkbox',
    widgetName: 'AppCheckbox',
    title: _t('AppCheckbox', 'AppCheckbox'),
    summary: _t(
      'Use AppCheckbox for multi-select and tristate flows, including boxed and selectbox variants.',
      'Dùng AppCheckbox cho multi-select và flow tristate, bao gồm boxed và selectbox variant.',
    ),
    quickStart: _t(
      "AppCheckbox(\n  value: true,\n  label: 'Remember this device',\n  onChanged: (value) {},\n)",
      "AppCheckbox(\n  value: true,\n  label: 'Ghi nhớ thiết bị này',\n  onChanged: (value) {},\n)",
    ),
    props: [
      _prop('value', 'bool?', '-', 'Current checked value. Supports null when tristate is enabled.', 'Giá trị checked hiện tại. Hỗ trợ null khi bật tristate.', required: true),
      _prop('onChanged', 'ValueChanged<bool?>?', '-', 'Receives the next checkbox value.', 'Nhận giá trị checkbox tiếp theo.'),
      _prop('size', 'AppCheckboxSize?', 'medium', 'Controls control size and label typography.', 'Điều khiển kích thước control và typography của label.'),
      _prop('variant', 'AppCheckboxVariant?', 'standard', 'standard, boxed, or selectbox.', 'standard, boxed hoặc selectbox.'),
      _prop('label', 'String?', '-', 'Plain text label content.', 'Nội dung label dạng text.'),
      _prop('labelWidget', 'Widget?', '-', 'Custom label widget.', 'Widget label tùy biến.'),
      _prop('labelPosition', 'AppCheckboxLabelPosition?', 'right', 'Places the label on the left or right side.', 'Đặt label bên trái hoặc phải.'),
      _prop('tristate', 'bool?', 'false', 'Allows null as an indeterminate value.', 'Cho phép null như giá trị trung gian.'),
      _prop('isDisabled', 'bool?', 'false', 'Fully disables interaction.', 'Tắt hoàn toàn khả năng tương tác.'),
      _prop('isReadOnly', 'bool?', 'false', 'Prevents changes while keeping the control readable.', 'Ngăn thay đổi nhưng vẫn hiển thị trạng thái để đọc.'),
      _prop('activeColor', 'Color?', 'ColorTokens.primary', 'Selected fill and border color.', 'Màu fill và viền khi được chọn.'),
      _prop('inactiveBackgroundColor', 'Color?', 'ColorTokens.white', 'Background color when unselected.', 'Màu nền khi chưa chọn.'),
      _prop('inactiveBorderColor', 'Color?', 'ColorTokens.borderDefault', 'Border color when unselected.', 'Màu viền khi chưa chọn.'),
      _prop('disabledBackgroundColor', 'Color?', 'ColorTokens.fillTertiary', 'Background color when disabled and unselected.', 'Màu nền khi disabled và chưa chọn.'),
      _prop('disabledBorderColor', 'Color?', 'ColorTokens.borderDefault', 'Border color when disabled.', 'Màu viền khi disabled.'),
      _prop('disabledSelectedColor', 'Color?', 'ColorTokens.fill', 'Fill color when disabled and selected.', 'Màu fill khi disabled và đã chọn.'),
      _prop('checkColor', 'Color?', 'ColorTokens.white', 'Checkmark color.', 'Màu của dấu check.'),
      _prop('labelColor', 'Color?', 'auto', 'Explicit label color override.', 'Ghi đè màu label.'),
      _prop('labelStyle', 'TextStyle?', '-', 'Custom label text style.', 'Text style tùy biến cho label.'),
      _prop('boxedBackgroundColor', 'Color?', 'ColorTokens.white', 'Background color for boxed/selectbox variants.', 'Màu nền cho boxed/selectbox variant.'),
      _prop('boxedBorderColor', 'Color?', 'ColorTokens.borderDefault', 'Border color for boxed/selectbox variants.', 'Màu viền cho boxed/selectbox variant.'),
      _prop('spacing', 'double?', 'size metric', 'Gap between control and label.', 'Khoảng cách giữa control và label.'),
      _prop('animationDuration', 'Duration?', '160ms', 'Animation duration for state changes.', 'Thời lượng animation khi đổi trạng thái.'),
      _prop('animationCurve', 'Curve?', 'Curves.easeOut', 'Animation curve for state changes.', 'Curve animation khi đổi trạng thái.'),
    ],
    examples: buildCheckboxExamples(),
  ),
  'app-radio': WidgetDocEntry(
    slug: 'app-radio',
    widgetName: 'AppRadio',
    title: _t('AppRadio', 'AppRadio'),
    summary: _t(
      'Use AppRadio when a user must choose exactly one value from a group.',
      'Dùng AppRadio khi người dùng phải chọn đúng một giá trị trong một nhóm.',
    ),
    quickStart: _t(
      "AppRadio<String>(\n  value: 'active',\n  groupValue: status,\n  label: 'Active',\n  onChanged: (value) {},\n)",
      "AppRadio<String>(\n  value: 'active',\n  groupValue: status,\n  label: 'Đang hoạt động',\n  onChanged: (value) {},\n)",
    ),
    props: [
      _prop('value', 'T', '-', 'Value represented by this radio option.', 'Giá trị được biểu diễn bởi radio này.', required: true),
      _prop('groupValue', 'T?', '-', 'Current selected group value.', 'Giá trị đang được chọn của cả nhóm.', required: true),
      _prop('onChanged', 'ValueChanged<T?>?', '-', 'Receives the selected value on tap.', 'Nhận giá trị được chọn khi nhấn.'),
      _prop('size', 'AppRadioSize?', 'medium', 'Controls control size and text size.', 'Điều khiển kích thước control và cỡ chữ.'),
      _prop('variant', 'AppRadioVariant?', 'standard', 'standard or boxed presentation.', 'Kiểu hiển thị standard hoặc boxed.'),
      _prop('label', 'String?', '-', 'Plain text label content.', 'Nội dung label dạng text.'),
      _prop('labelWidget', 'Widget?', '-', 'Custom label widget.', 'Widget label tùy biến.'),
      _prop('labelPosition', 'AppRadioLabelPosition?', 'right', 'Places the label left or right of the control.', 'Đặt label bên trái hoặc phải control.'),
      _prop('isDisabled', 'bool?', 'false', 'Fully disables interaction.', 'Tắt hoàn toàn tương tác.'),
      _prop('isReadOnly', 'bool?', 'false', 'Prevents changes while keeping the control visible.', 'Ngăn thay đổi nhưng vẫn hiển thị trạng thái để đọc.'),
      _prop('activeColor', 'Color?', 'ColorTokens.primary', 'Color of the selected ring and dot.', 'Màu của viền và chấm khi được chọn.'),
      _prop('inactiveBorderColor', 'Color?', 'ColorTokens.borderDefault', 'Border color when unselected.', 'Màu viền khi chưa chọn.'),
      _prop('disabledBorderColor', 'Color?', 'ColorTokens.borderDefault', 'Border color when disabled.', 'Màu viền khi disabled.'),
      _prop('disabledFillColor', 'Color?', 'ColorTokens.fillTertiary', 'Outer fill color when disabled.', 'Màu nền ngoài khi disabled.'),
      _prop('disabledSelectedColor', 'Color?', 'ColorTokens.gray', 'Inner dot color when disabled and selected.', 'Màu chấm bên trong khi disabled và đã chọn.'),
      _prop('labelColor', 'Color?', 'auto', 'Explicit label color override.', 'Ghi đè màu label.'),
      _prop('labelStyle', 'TextStyle?', '-', 'Custom label text style.', 'Text style tùy biến cho label.'),
      _prop('boxedBackgroundColor', 'Color?', 'ColorTokens.white', 'Background color for boxed mode.', 'Màu nền của boxed mode.'),
      _prop('boxedBorderColor', 'Color?', 'ColorTokens.borderDefault', 'Border color for boxed mode.', 'Màu viền của boxed mode.'),
      _prop('spacing', 'double?', 'size metric', 'Gap between the control and label.', 'Khoảng cách giữa control và label.'),
      _prop('animationDuration', 'Duration?', '160ms', 'Animation duration for state transitions.', 'Thời lượng animation khi đổi trạng thái.'),
      _prop('animationCurve', 'Curve?', 'Curves.easeOut', 'Animation curve for state transitions.', 'Curve animation khi đổi trạng thái.'),
    ],
    examples: buildRadioExamples(),
  ),
  'app-switch': WidgetDocEntry(
    slug: 'app-switch',
    widgetName: 'AppSwitch',
    title: _t('AppSwitch', 'AppSwitch'),
    summary: _t(
      'Use AppSwitch for fast on and off preferences that should take effect immediately.',
      'Dùng AppSwitch cho các tùy chọn bật tắt có hiệu lực ngay lập tức.',
    ),
    quickStart: _t(
      "AppSwitch(\n  value: true,\n  label: 'Enable notifications',\n  onChanged: (value) {},\n)",
      "AppSwitch(\n  value: true,\n  label: 'Bật thông báo',\n  onChanged: (value) {},\n)",
    ),
    props: [
      _prop('value', 'bool', '-', 'Current on and off state.', 'Trạng thái bật tắt hiện tại.', required: true),
      _prop('onChanged', 'ValueChanged<bool>?', '-', 'Receives the next state after a tap.', 'Nhận trạng thái tiếp theo sau khi nhấn.'),
      _prop('size', 'AppSwitchSize?', 'medium', 'Controls the track, thumb, and label metrics.', 'Điều khiển kích thước track, thumb và label.'),
      _prop('label', 'String?', '-', 'Plain text label content.', 'Nội dung label dạng text.'),
      _prop('labelWidget', 'Widget?', '-', 'Custom label widget.', 'Widget label tùy biến.'),
      _prop('labelPosition', 'AppSwitchLabelPosition?', 'right', 'Places the label left or right of the control.', 'Đặt label bên trái hoặc phải của control.'),
      _prop('isDisabled', 'bool?', 'false', 'Fully disables interaction.', 'Tắt hoàn toàn tương tác.'),
      _prop('isReadOnly', 'bool?', 'false', 'Prevents changes while keeping the state visible.', 'Ngăn thay đổi nhưng vẫn hiển thị trạng thái.'),
      _prop('activeTrackColor', 'Color?', 'ColorTokens.primary', 'Track color when switched on.', 'Màu track khi bật.'),
      _prop('inactiveTrackColor', 'Color?', 'ColorTokens.fill', 'Track color when switched off.', 'Màu track khi tắt.'),
      _prop('disabledActiveTrackColor', 'Color?', 'ColorTokens.borderOutline', 'Track color when disabled and on.', 'Màu track khi disabled và đang bật.'),
      _prop('disabledInactiveTrackColor', 'Color?', 'ColorTokens.fillSecondary', 'Track color when disabled and off.', 'Màu track khi disabled và đang tắt.'),
      _prop('activeThumbColor', 'Color?', 'ColorTokens.white', 'Thumb color when switched on.', 'Màu thumb khi bật.'),
      _prop('inactiveThumbColor', 'Color?', 'ColorTokens.white', 'Thumb color when switched off.', 'Màu thumb khi tắt.'),
      _prop('disabledThumbColor', 'Color?', 'ColorTokens.white', 'Thumb color when disabled.', 'Màu thumb khi disabled.'),
      _prop('labelColor', 'Color?', 'auto', 'Explicit label color override.', 'Ghi đè màu label.'),
      _prop('labelStyle', 'TextStyle?', '-', 'Custom label text style.', 'Text style tùy biến cho label.'),
      _prop('spacing', 'double?', 'size metric', 'Gap between the switch and label.', 'Khoảng cách giữa switch và label.'),
      _prop('animationDuration', 'Duration?', '180ms', 'Animation duration for toggling.', 'Thời lượng animation khi chuyển trạng thái.'),
      _prop('animationCurve', 'Curve?', 'Curves.easeOut', 'Animation curve for toggling.', 'Curve animation khi chuyển trạng thái.'),
    ],
    examples: buildSwitchExamples(),
  ),
  'app-text-field': WidgetDocEntry(
    slug: 'app-text-field',
    widgetName: 'AppTextField',
    title: _t('AppTextField', 'AppTextField'),
    summary: _t(
      'Use AppTextField for generic form input, validation, prefix and suffix composition, and semantic status states.',
      'Dùng AppTextField cho nhập liệu tổng quát, validate, ghép prefix suffix và các trạng thái semantic.',
    ),
    quickStart: _t(
      "AppTextField(\n  labelText: 'Customer name',\n  hintText: 'Enter customer name',\n  prefixIcon: const Icon(Icons.person_outline),\n)",
      "AppTextField(\n  labelText: 'Tên khách hàng',\n  hintText: 'Nhập tên khách hàng',\n  prefixIcon: const Icon(Icons.person_outline),\n)",
    ),
    props: [
      _prop('variant', 'AppTextFieldVariant', 'primary', 'Semantic palette variant.', 'Biến thể màu semantic.'),
      _prop('isRounded', 'bool?', '-', 'Uses rounded field shape when true.', 'Dùng field bo tròn khi true.'),
      _prop('size', 'AppTextFieldSize', 'medium', 'Controls field height and typography.', 'Điều khiển chiều cao field và typography.'),
      _prop('hintText', 'String?', '-', 'Placeholder shown when empty.', 'Placeholder hiển thị khi trống.'),
      _prop('labelText', 'String?', '-', 'Field label content.', 'Nội dung label của field.'),
      _prop('helperText', 'String?', '-', 'Supporting helper text below the field.', 'Text hỗ trợ hiển thị dưới field.'),
      _prop('errorText', 'String?', '-', 'Explicit error text override.', 'Ghi đè text lỗi cụ thể.'),
      _prop('errorTextSize', 'AppTextSize?', '-', 'Custom typography token for the error text.', 'Token typography riêng cho error text.'),
      _prop('isPassword', 'bool?', '-', 'Treats content as obscured password text.', 'Xử lý nội dung như mật khẩu bị ẩn.'),
      _prop('isReadOnly', 'bool?', '-', 'Prevents user edits while allowing focus.', 'Ngăn chỉnh sửa nhưng vẫn cho phép focus.'),
      _prop('isDisabled', 'bool?', '-', 'Fully disables the field.', 'Tắt hoàn toàn field.'),
      _prop('isError', 'bool?', '-', 'Forces error state styling.', 'Ép hiển thị style lỗi.'),
      _prop('isSuccess', 'bool?', '-', 'Forces success state styling.', 'Ép hiển thị style thành công.'),
      _prop('isWarning', 'bool?', '-', 'Forces warning state styling.', 'Ép hiển thị style cảnh báo.'),
      _prop('isInfo', 'bool?', '-', 'Forces info state styling.', 'Ép hiển thị style thông tin.'),
      _prop('isRequired', 'bool?', '-', 'Marks the field label as required.', 'Đánh dấu label là bắt buộc.'),
      _prop('isOptional', 'bool?', '-', 'Marks the field label as optional.', 'Đánh dấu label là tùy chọn.'),
      _prop('prefixIcon', 'Widget?', '-', 'Leading icon inside the input chrome.', 'Icon đầu vào nằm bên trong input.'),
      _prop('suffixIcon', 'Widget?', '-', 'Trailing icon inside the input chrome.', 'Icon cuối vào nằm bên trong input.'),
      _prop('clearTextIcon', 'Widget?', '-', 'Custom clear action icon.', 'Icon tùy biến cho hành động xóa nội dung.'),
      _prop('prefix', 'Widget?', '-', 'Custom leading content slot.', 'Slot nội dung tùy biến phía trước.'),
      _prop('suffix', 'Widget?', '-', 'Custom trailing content slot.', 'Slot nội dung tùy biến phía sau.'),
      _prop('showClearTextAction', 'bool', 'true', 'Shows the clear-text affordance when content is not empty.', 'Hiển thị affordance xóa nội dung khi field không trống.'),
      _prop('floatingLabelBehavior', 'FloatingLabelBehavior?', 'always', 'How the label floats relative to field focus and value.', 'Cách label nổi lên theo focus và giá trị của field.'),
      _prop('controller', 'TextEditingController?', '-', 'External text controller.', 'Text controller bên ngoài.'),
      _prop('focusNode', 'FocusNode?', '-', 'External focus node.', 'Focus node bên ngoài.'),
      _prop('onChanged', 'ValueChanged<String>?', '-', 'Called when the text changes.', 'Được gọi khi nội dung thay đổi.'),
      _prop('onTap', 'VoidCallback?', '-', 'Callback when the field is tapped.', 'Callback khi chạm vào field.'),
      _prop('validate', 'String? Function(String value)?', '-', 'Returns an error string for the current value.', 'Trả về chuỗi lỗi cho giá trị hiện tại.'),
      _prop('keyboardType', 'TextInputType?', '-', 'Keyboard type hint for the platform.', 'Gợi ý loại bàn phím cho nền tảng.'),
      _prop('textInputAction', 'TextInputAction?', '-', 'Action button shown on the keyboard.', 'Hành động hiển thị trên bàn phím.'),
      _prop('autofocus', 'bool', 'false', 'Requests focus on first build.', 'Tự động xin focus ở lần build đầu tiên.'),
      _prop('maxLength', 'int?', '-', 'Maximum input length.', 'Độ dài tối đa của dữ liệu nhập.'),
    ],
    examples: buildTextFieldExamples(),
  ),
  'app-password-field': WidgetDocEntry(
    slug: 'app-password-field',
    widgetName: 'AppPasswordField',
    title: _t('AppPasswordField', 'AppPasswordField'),
    summary: _t(
      'Use AppPasswordField for password entry with built-in visibility toggle and password-friendly defaults.',
      'Dùng AppPasswordField cho nhập mật khẩu với nút ẩn hiện tích hợp và các mặc định phù hợp cho mật khẩu.',
    ),
    quickStart: _t(
      "AppPasswordField(\n  labelText: 'Password',\n  hintText: 'Enter your password',\n  helperText: 'Minimum 8 characters',\n)",
      "AppPasswordField(\n  labelText: 'Mật khẩu',\n  hintText: 'Nhập mật khẩu',\n  helperText: 'Tối thiểu 8 ký tự',\n)",
    ),
    props: [
      _prop('variant', 'AppTextFieldVariant', 'primary', 'Semantic palette variant.', 'Biến thể màu semantic.'),
      _prop('isRounded', 'bool?', '-', 'Uses rounded field shape when true.', 'Dùng field bo tròn khi true.'),
      _prop('size', 'AppTextFieldSize', 'medium', 'Controls field height and typography.', 'Điều khiển chiều cao field và typography.'),
      _prop('hintText', 'String?', 'Nhập mật khẩu', 'Placeholder shown when empty.', 'Placeholder hiển thị khi trống.'),
      _prop('labelText', 'String?', '-', 'Field label content.', 'Nội dung label của field.'),
      _prop('helperText', 'String?', '-', 'Supporting helper text below the field.', 'Text hỗ trợ dưới field.'),
      _prop('errorText', 'String?', '-', 'Explicit error text override.', 'Ghi đè text lỗi cụ thể.'),
      _prop('errorTextSize', 'AppTextSize?', '-', 'Custom typography token for the error text.', 'Token typography riêng cho error text.'),
      _prop('isReadOnly', 'bool', 'false', 'Prevents edits while keeping the field visible.', 'Ngăn chỉnh sửa nhưng vẫn hiển thị field.'),
      _prop('isDisabled', 'bool', 'false', 'Fully disables the field.', 'Tắt hoàn toàn field.'),
      _prop('isError', 'bool', 'false', 'Forces error styling.', 'Ép hiển thị style lỗi.'),
      _prop('isSuccess', 'bool', 'false', 'Forces success styling.', 'Ép hiển thị style thành công.'),
      _prop('isWarning', 'bool', 'false', 'Forces warning styling.', 'Ép hiển thị style cảnh báo.'),
      _prop('isRequired', 'bool', 'false', 'Marks the label as required.', 'Đánh dấu label là bắt buộc.'),
      _prop('isOptional', 'bool', 'false', 'Marks the label as optional.', 'Đánh dấu label là tùy chọn.'),
      _prop('autofocus', 'bool', 'false', 'Requests focus on first build.', 'Tự động xin focus ở lần build đầu tiên.'),
      _prop('showVisibilityToggle', 'bool', 'true', 'Shows the eye icon toggle.', 'Hiển thị nút icon ẩn hiện mật khẩu.'),
      _prop('showClearTextAction', 'bool', 'false', 'Enables the inherited clear-text action.', 'Bật hành động xóa nội dung kế thừa từ AppTextField.'),
      _prop('initiallyObscured', 'bool', 'true', 'Starts with obscured password text.', 'Khởi tạo với nội dung đang bị ẩn.'),
      _prop('prefixIcon', 'Widget?', 'lock icon when prefix is empty', 'Explicit prefix icon override.', 'Ghi đè prefix icon cụ thể.'),
      _prop('visibleIcon', 'Widget?', 'Icons.visibility_outlined', 'Icon used when the password is visible.', 'Icon dùng khi mật khẩu đang hiển thị.'),
      _prop('obscuredIcon', 'Widget?', 'Icons.visibility_off_outlined', 'Icon used when the password is hidden.', 'Icon dùng khi mật khẩu đang bị ẩn.'),
      _prop('clearTextIcon', 'Widget?', '-', 'Custom clear action icon.', 'Icon tùy biến cho hành động xóa nội dung.'),
      _prop('prefix', 'Widget?', '-', 'Custom leading content slot.', 'Slot nội dung tùy biến phía trước.'),
      _prop('suffix', 'Widget?', '-', 'Custom trailing content shown before the visibility toggle.', 'Slot nội dung phía sau, hiển thị trước nút ẩn hiện.'),
      _prop('floatingLabelBehavior', 'FloatingLabelBehavior?', 'always', 'How the label floats relative to field state.', 'Cách label nổi lên theo trạng thái của field.'),
      _prop('controller', 'TextEditingController?', '-', 'External text controller.', 'Text controller bên ngoài.'),
      _prop('focusNode', 'FocusNode?', '-', 'External focus node.', 'Focus node bên ngoài.'),
      _prop('onChanged', 'ValueChanged<String>?', '-', 'Called when the value changes.', 'Được gọi khi giá trị thay đổi.'),
      _prop('onVisibilityChanged', 'ValueChanged<bool>?', '-', 'Reports whether the field is currently obscured.', 'Báo trạng thái field hiện đang ẩn hay hiện mật khẩu.'),
      _prop('onTap', 'VoidCallback?', '-', 'Callback when the field is tapped.', 'Callback khi chạm vào field.'),
      _prop('validate', 'String? Function(String value)?', '-', 'Returns an error string for the current value.', 'Trả về chuỗi lỗi cho giá trị hiện tại.'),
      _prop('textInputAction', 'TextInputAction?', '-', 'Action button shown on the keyboard.', 'Hành động hiển thị trên bàn phím.'),
      _prop('maxLength', 'int?', '-', 'Maximum password length.', 'Độ dài tối đa của mật khẩu.'),
    ],
    examples: buildPasswordFieldExamples(),
  ),
  'app-search-field': WidgetDocEntry(
    slug: 'app-search-field',
    widgetName: 'AppSearchField',
    title: _t('AppSearchField', 'AppSearchField'),
    summary: _t(
      'Use AppSearchField when you need a search-first input with debounced callbacks and compact icon composition.',
      'Dùng AppSearchField khi bạn cần input ưu tiên tìm kiếm với callback debounce và cách ghép icon gọn nhẹ.',
    ),
    quickStart: _t(
      "AppSearchField(\n  hintText: 'Search products',\n  onSearchChanged: (value) {},\n)",
      "AppSearchField(\n  hintText: 'Tìm sản phẩm',\n  onSearchChanged: (value) {},\n)",
    ),
    props: [
      _prop('controller', 'TextEditingController?', '-', 'External text controller.', 'Text controller bên ngoài.'),
      _prop('focusNode', 'FocusNode?', '-', 'External focus node.', 'Focus node bên ngoài.'),
      _prop('onChanged', 'ValueChanged<String>?', '-', 'Immediate callback for every keystroke.', 'Callback tức thời cho mỗi lần gõ.'),
      _prop('onSearchChanged', 'ValueChanged<String>?', '-', 'Debounced callback for search requests.', 'Callback debounce cho truy vấn tìm kiếm.'),
      _prop('hintText', 'String', 'Tìm kiếm...', 'Placeholder shown when empty.', 'Placeholder hiển thị khi trống.'),
      _prop('searchDelay', 'int', '400', 'Debounce duration in milliseconds.', 'Thời gian debounce tính bằng mili giây.'),
      _prop('size', 'AppTextFieldSize', 'medium', 'Controls the size of the underlying text field.', 'Điều khiển kích thước của text field bên dưới.'),
      _prop('autofocus', 'bool', 'false', 'Requests focus on first build.', 'Tự động xin focus ở lần build đầu tiên.'),
      _prop('isDisabled', 'bool', 'false', 'Fully disables the field.', 'Tắt hoàn toàn field.'),
      _prop('isReadOnly', 'bool', 'false', 'Prevents edits while allowing selection and focus.', 'Ngăn chỉnh sửa nhưng vẫn cho phép chọn và focus.'),
      _prop('prefixIcons', 'List<Widget>?', '-', 'Group of widgets rendered in the prefix slot.', 'Nhóm widget hiển thị trong prefix slot.'),
      _prop('prefixIcon', 'Widget?', 'Icons.search_rounded', 'Leading icon inside the input when no prefix group is used.', 'Icon dẫn đầu trong input khi không dùng prefix group.'),
      _prop('suffixIcons', 'List<Widget>?', '-', 'Group of widgets rendered in the suffix slot.', 'Nhóm widget hiển thị trong suffix slot.'),
      _prop('suffixIcon', 'Widget?', '-', 'Trailing icon inside the input chrome.', 'Icon cuối nằm trong input.'),
      _prop('helperText', 'String?', '-', 'Supporting helper text below the field.', 'Text hỗ trợ dưới field.'),
      _prop('errorText', 'String?', '-', 'Explicit error text below the field.', 'Text lỗi cụ thể hiển thị dưới field.'),
    ],
    examples: buildSearchFieldExamples(),
  ),
  'app-otp-field': WidgetDocEntry(
    slug: 'app-otp-field',
    widgetName: 'AppOtpField',
    title: _t('AppOtpField', 'AppOtpField'),
    summary: _t(
      'Use AppOtpField when users need to enter an SMS, email, or authenticator code with clean digit-only behavior.',
      'Dùng AppOtpField khi người dùng cần nhập mã SMS, email hoặc mã xác thực với hành vi digit-only gọn gàng.',
    ),
    quickStart: _t(
      "AppOtpField(\n  onChanged: (value) {},\n  onCompleted: (value) {},\n)",
      "AppOtpField(\n  onChanged: (value) {},\n  onCompleted: (value) {},\n)",
    ),
    props: [
      _prop('length', 'int', '6', 'Number of OTP cells and max digits.', 'Số ô OTP và số digit tối đa.'),
      _prop('controller', 'TextEditingController?', '-', 'External text controller.', 'Text controller bên ngoài.'),
      _prop('focusNode', 'FocusNode?', '-', 'External focus node.', 'Focus node bên ngoài.'),
      _prop('onChanged', 'ValueChanged<String>?', '-', 'Called whenever the sanitized OTP changes.', 'Được gọi mỗi khi OTP sau khi sanitize thay đổi.'),
      _prop('onCompleted', 'ValueChanged<String>?', '-', 'Called when the OTP reaches the configured length.', 'Được gọi khi OTP đạt đủ độ dài đã cấu hình.'),
      _prop('autofocus', 'bool', 'false', 'Requests focus on first build.', 'Tự động xin focus ở lần build đầu tiên.'),
      _prop('isDisabled', 'bool', 'false', 'Disables focus and text entry.', 'Vô hiệu hóa focus và nhập liệu.'),
      _prop('cellWidth', 'double', '48', 'Base width of each OTP cell.', 'Chiều rộng cơ bản của mỗi ô OTP.'),
      _prop('cellHeight', 'double', '56', 'Height of each OTP cell.', 'Chiều cao của mỗi ô OTP.'),
      _prop('cellSpacing', 'double', 'SpacingTokens.spaceM', 'Horizontal gap between OTP cells.', 'Khoảng cách ngang giữa các ô OTP.'),
      _prop('borderRadius', 'BorderRadiusGeometry?', 'RadiusTokens.radiusLgBorderRadius', 'Border radius used by each cell.', 'Bo góc áp dụng cho từng ô OTP.'),
    ],
    examples: buildOtpExamples(),
  ),
  'app-date-time-field': WidgetDocEntry(
    slug: 'app-date-time-field',
    widgetName: 'AppDateTimeField',
    title: _t('AppDateTimeField', 'AppDateTimeField'),
    summary: _t(
      'Use AppDateTimeField to collect date, time, or combined date-time values while keeping the same visual language as other inputs.',
      'Dùng AppDateTimeField để thu thập ngày, giờ hoặc ngày-giờ trong cùng ngôn ngữ hiển thị với các input khác.',
    ),
    quickStart: _t(
      "AppDateTimeField(\n  mode: AppDateTimeFieldMode.date,\n  labelText: 'Delivery date',\n  onChanged: (value) {},\n)",
      "AppDateTimeField(\n  mode: AppDateTimeFieldMode.date,\n  labelText: 'Ngày giao hàng',\n  onChanged: (value) {},\n)",
    ),
    props: [
      _prop('mode', 'AppDateTimeFieldMode', 'date', 'date, time, or dateTime mode.', 'Chế độ date, time hoặc dateTime.'),
      _prop('value', 'DateTime?', '-', 'Current selected date or date-time value.', 'Giá trị ngày hoặc ngày-giờ hiện được chọn.'),
      _prop('timeValue', 'TimeOfDay?', '-', 'Current selected time value in time mode.', 'Giá trị giờ hiện được chọn trong mode time.'),
      _prop('onChanged', 'ValueChanged<DateTime?>?', '-', 'Receives the selected date or date-time.', 'Nhận ngày hoặc ngày-giờ đã chọn.'),
      _prop('onTimeChanged', 'ValueChanged<TimeOfDay?>?', '-', 'Receives the selected time.', 'Nhận giờ đã chọn.'),
      _prop('variant', 'AppTextFieldVariant', 'primary', 'Semantic palette variant.', 'Biến thể màu semantic.'),
      _prop('size', 'AppTextFieldSize', 'medium', 'Controls the size of the underlying field.', 'Điều khiển kích thước field bên dưới.'),
      _prop('isRounded', 'bool', 'false', 'Uses rounded field shape.', 'Dùng field bo tròn.'),
      _prop('hintText', 'String?', 'mode default', 'Placeholder shown before a selection is made.', 'Placeholder trước khi người dùng chọn giá trị.'),
      _prop('labelText', 'String?', '-', 'Field label content.', 'Nội dung label của field.'),
      _prop('helperText', 'String?', '-', 'Supporting helper text below the field.', 'Text hỗ trợ dưới field.'),
      _prop('errorText', 'String?', '-', 'Explicit error text override.', 'Ghi đè text lỗi cụ thể.'),
      _prop('errorTextSize', 'AppTextSize?', '-', 'Custom typography token for the error text.', 'Token typography riêng cho error text.'),
      _prop('isDisabled', 'bool', 'false', 'Fully disables the field.', 'Tắt hoàn toàn field.'),
      _prop('isRequired', 'bool', 'false', 'Marks the label as required.', 'Đánh dấu label là bắt buộc.'),
      _prop('isOptional', 'bool', 'false', 'Marks the label as optional.', 'Đánh dấu label là tùy chọn.'),
      _prop('prefixIcon', 'Widget?', '-', 'Leading icon inside the input chrome.', 'Icon đầu vào bên trong input.'),
      _prop('suffixIcon', 'Widget?', 'calendar/clock icon by mode', 'Trailing icon override.', 'Ghi đè icon cuối theo mode.'),
      _prop('prefix', 'Widget?', '-', 'Custom leading content slot.', 'Slot nội dung tùy biến phía trước.'),
      _prop('suffix', 'Widget?', '-', 'Custom trailing content slot.', 'Slot nội dung tùy biến phía sau.'),
      _prop('floatingLabelBehavior', 'FloatingLabelBehavior?', 'always', 'How the label floats relative to state.', 'Cách label nổi lên theo trạng thái.'),
      _prop('focusNode', 'FocusNode?', '-', 'External focus node.', 'Focus node bên ngoài.'),
      _prop('autofocus', 'bool', 'false', 'Requests focus on first build.', 'Tự động xin focus ở lần build đầu tiên.'),
      _prop('firstDate', 'DateTime?', '-', 'Lower bound for date selection.', 'Giới hạn nhỏ nhất cho việc chọn ngày.'),
      _prop('lastDate', 'DateTime?', '-', 'Upper bound for date selection.', 'Giới hạn lớn nhất cho việc chọn ngày.'),
      _prop('initialPickerDate', 'DateTime?', '-', 'Initial date shown when the picker opens.', 'Ngày mặc định khi mở picker.'),
      _prop('initialPickerTime', 'TimeOfDay?', '-', 'Initial time shown when the picker opens.', 'Giờ mặc định khi mở picker.'),
      _prop('datePicker', 'AppDatePicker?', '-', 'Custom date picker implementation.', 'Implementation tùy biến cho date picker.'),
      _prop('timePicker', 'AppTimePicker?', '-', 'Custom time picker implementation.', 'Implementation tùy biến cho time picker.'),
      _prop('dateFormatter', 'AppDateFormatter?', '-', 'Custom formatter for date mode.', 'Formatter tùy biến cho mode date.'),
      _prop('timeFormatter', 'AppTimeFormatter?', '-', 'Custom formatter for time mode.', 'Formatter tùy biến cho mode time.'),
      _prop('dateTimeFormatter', 'AppDateTimeFormatter?', '-', 'Custom formatter for date-time mode.', 'Formatter tùy biến cho mode date-time.'),
      _prop('pickerStyle', 'AppDateTimePickerStyle?', '-', 'Customizes colors and copy inside the picker flow.', 'Tùy biến màu và text trong flow picker.'),
      _prop('pickerPresentation', 'AppDateTimePickerPresentation', 'dialog', 'dialog or bottomSheet presentation.', 'Kiểu hiển thị dialog hoặc bottomSheet.'),
      _prop('initialDatePickerEntryMode', 'DatePickerEntryMode', 'calendar', 'Initial entry mode for the date picker.', 'Entry mode ban đầu của date picker.'),
      _prop('initialTimePickerEntryMode', 'TimePickerEntryMode', 'dial', 'Initial entry mode for the time picker.', 'Entry mode ban đầu của time picker.'),
      _prop('selectableDayPredicate', 'SelectableDayPredicate?', '-', 'Disables dates that should not be selectable.', 'Vô hiệu hóa các ngày không được phép chọn.'),
    ],
    examples: buildDateTimeExamples(),
  ),
  'app-dropdown': WidgetDocEntry(
    slug: 'app-dropdown',
    widgetName: 'AppDropdown',
    title: _t('AppDropdown', 'AppDropdown'),
    summary: _t(
      'Use AppDropdown for local or remote selectable lists with search, loading, empty, error, and pagination states.',
      'Dùng AppDropdown cho danh sách chọn local hoặc remote với các trạng thái search, loading, empty, error và phân trang.',
    ),
    quickStart: _t(
      "AppDropdown<String>(\n  items: statuses,\n  value: selected,\n  hintText: 'Choose status',\n  itemAsString: (item) => item,\n  onChanged: (value) {},\n)",
      "AppDropdown<String>(\n  items: statuses,\n  value: selected,\n  hintText: 'Chọn trạng thái',\n  itemAsString: (item) => item,\n  onChanged: (value) {},\n)",
    ),
    props: [
      _prop('labelText', 'String?', '-', 'Optional field label above the trigger.', 'Label tùy chọn phía trên trigger.'),
      _prop('hintText', 'String', '-', 'Placeholder text when no item is selected.', 'Placeholder khi chưa chọn item.', required: true),
      _prop('items', 'List<T>', '-', 'Selectable options.', 'Danh sách tùy chọn.', required: true),
      _prop('value', 'T?', '-', 'Current selected value.', 'Giá trị đang được chọn.', required: true),
      _prop('onChanged', 'ValueChanged<T?>?', '-', 'Receives the next selected value.', 'Nhận giá trị được chọn tiếp theo.', required: true),
      _prop('itemAsString', 'String Function(T)', '-', 'Maps each item to the visible label.', 'Chuyển mỗi item thành text hiển thị.', required: true),
      _prop('suffixIcon', 'Widget?', 'chevron icon', 'Trigger trailing icon override.', 'Ghi đè icon cuối của trigger.'),
      _prop('prefixIcon', 'Widget?', '-', 'Trigger leading icon.', 'Icon đầu của trigger.'),
      _prop('isSearchable', 'bool?', 'false', 'Shows the search field inside the menu.', 'Hiển thị ô search bên trong menu.'),
      _prop('emptyText', 'String?', 'No results found', 'Empty state message.', 'Thông điệp khi không có kết quả.'),
      _prop('searchHintText', 'String?', 'Search...', 'Placeholder for the search field.', 'Placeholder của ô search.'),
      _prop('isLoading', 'bool', 'false', 'Shows the loading state for initial data.', 'Hiển thị trạng thái loading cho dữ liệu ban đầu.'),
      _prop('errorText', 'String?', '-', 'Error message shown inside the menu state.', 'Thông điệp lỗi hiển thị trong menu.'),
      _prop('onMenuOpen', 'VoidCallback?', '-', 'Called when the menu opens.', 'Được gọi khi menu mở.'),
      _prop('onRetry', 'VoidCallback?', '-', 'Retry callback for the error state.', 'Callback retry cho trạng thái lỗi.'),
      _prop('onSearchChanged', 'ValueChanged<String>?', '-', 'Search callback, especially useful for remote mode.', 'Callback search, đặc biệt hữu ích ở remote mode.'),
      _prop('enableLocalFilter', 'bool', 'true', 'Filters client-side or delegates to remote search.', 'Lọc phía client hoặc ủy quyền cho remote search.'),
      _prop('hasMore', 'bool', 'false', 'Whether more results can be paged in.', 'Cho biết còn dữ liệu để nạp tiếp hay không.'),
      _prop('isLoadingMore', 'bool', 'false', 'Shows the loading-more footer.', 'Hiển thị footer loading more.'),
      _prop('onLoadMore', 'VoidCallback?', '-', 'Pagination callback when the menu nears the bottom.', 'Callback phân trang khi menu cuộn gần đáy.'),
      _prop('menuMaxHeight', 'double', 'AppDropdownTokens.defaultMenuMaxHeight', 'Maximum height of the menu panel.', 'Chiều cao tối đa của panel menu.'),
      _prop('loadMoreTriggerOffset', 'double', 'AppDropdownTokens.defaultLoadMoreTriggerOffset', 'Scroll threshold before triggering load more.', 'Ngưỡng cuộn trước khi kích hoạt load more.'),
      _prop('isShowStripedBg', 'bool', 'false', 'Enables striped item background styling.', 'Bật kiểu nền xen kẽ cho item.'),
      _prop('resetSearchOnMenuOpen', 'bool', 'true', 'Clears the current search value when the menu reopens.', 'Xóa từ khóa tìm kiếm hiện tại khi mở menu lại.'),
      _prop('size', 'AppDropdownSize', 'medium', 'Controls trigger height and menu metrics.', 'Điều khiển chiều cao trigger và metric của menu.'),
      _prop('isDisabled', 'bool', 'false', 'Fully disables the dropdown trigger.', 'Tắt hoàn toàn trigger của dropdown.'),
    ],
    examples: buildDropdownExamples(),
  ),
  'app-alert': WidgetDocEntry(
    slug: 'app-alert',
    widgetName: 'AppAlert',
    title: _t('AppAlert', 'AppAlert'),
    summary: _t(
      'Use AppAlert for inline feedback and AppAlert.show for overlay alerts with placement, auto close, and status-driven styling.',
      'Dùng AppAlert cho phản hồi inline và AppAlert.show cho alert overlay với placement, auto close và style theo trạng thái.',
    ),
    quickStart: _t(
      "AppAlert.show(\n  context: context,\n  title: 'Saved',\n  type: AppAlertType.success,\n  description: 'Changes were published successfully.',\n)",
      "AppAlert.show(\n  context: context,\n  title: 'Đã lưu',\n  type: AppAlertType.success,\n  description: 'Thay đổi đã được publish thành công.',\n)",
    ),
    props: [
      _prop('type', 'AppAlertType', 'info', 'Status style such as info, warning, danger, or success.', 'Kiểu trạng thái như info, warning, danger hoặc success.'),
      _prop('size', 'AppAlertSize', 'medium', 'Controls alert width, spacing, and typography.', 'Điều khiển chiều rộng, spacing và typography của alert.'),
      _prop('title', 'String', '-', 'Main alert title.', 'Tiêu đề chính của alert.', required: true),
      _prop('description', 'String?', '-', 'Optional supporting message.', 'Nội dung mô tả tùy chọn.'),
      _prop('actions', 'List<AppAlertAction>', 'const []', 'Inline action list rendered below the content.', 'Danh sách action hiển thị dưới nội dung.'),
      _prop('visible', 'bool', 'true', 'Controls whether the inline alert is shown.', 'Điều khiển việc hiển thị alert inline.'),
      _prop('dismissible', 'bool', 'true', 'Whether the alert can be manually dismissed.', 'Cho biết alert có thể được đóng thủ công hay không.'),
      _prop('showIcon', 'bool', 'true', 'Shows the semantic leading icon.', 'Hiển thị icon semantic ở đầu.'),
      _prop('showCloseIcon', 'bool', 'true', 'Shows the close icon button.', 'Hiển thị nút icon đóng.'),
      _prop('onClose', 'VoidCallback?', '-', 'Called when the user requests a close action.', 'Được gọi khi người dùng yêu cầu đóng.'),
      _prop('onClosed', 'VoidCallback?', '-', 'Called after the alert has fully closed.', 'Được gọi sau khi alert đóng hoàn toàn.'),
      _prop('icon', 'Widget?', 'type default', 'Custom leading icon widget.', 'Widget icon đầu tùy biến.'),
      _prop('closeIcon', 'Widget?', 'Icons.close', 'Custom trailing close icon widget.', 'Widget icon đóng tùy biến.'),
      _prop('backgroundColor', 'Color?', 'type default', 'Explicit alert background override.', 'Ghi đè màu nền của alert.'),
      _prop('iconColor', 'Color?', 'type default', 'Explicit leading icon color override.', 'Ghi đè màu icon đầu.'),
      _prop('titleColor', 'Color?', 'type default', 'Explicit title color override.', 'Ghi đè màu của tiêu đề.'),
      _prop('descriptionColor', 'Color?', 'type default', 'Explicit description color override.', 'Ghi đè màu của mô tả.'),
      _prop('actionColor', 'Color?', 'type default', 'Explicit action color override.', 'Ghi đè màu của action.'),
      _prop('width', 'double?', 'size default', 'Custom width for the alert surface.', 'Chiều rộng tùy biến của alert.'),
      _prop('padding', 'EdgeInsetsGeometry?', 'size default', 'Custom internal padding.', 'Padding bên trong tùy biến.'),
      _prop('animationDuration', 'Duration', '180ms', 'Animation duration for showing and hiding.', 'Thời lượng animation khi hiện và ẩn.'),
      _prop('animationCurve', 'Curve', 'Curves.easeOut', 'Animation curve for showing and hiding.', 'Curve animation khi hiện và ẩn.'),
    ],
    examples: buildAlertExamples(),
  ),
  'app-bottom-sheet': WidgetDocEntry(
    slug: 'app-bottom-sheet',
    widgetName: 'AppBottomSheet',
    title: _t('AppBottomSheet', 'AppBottomSheet'),
    summary: _t(
      'Use AppBottomSheet for contextual tasks, filters, and compact forms that should stay anchored to the bottom edge.',
      'Dùng AppBottomSheet cho tác vụ theo ngữ cảnh, bộ lọc và form ngắn cần neo ở cạnh dưới.',
    ),
    quickStart: _t(
      "AppBottomSheet.show<void>(\n  context: context,\n  builder: (sheetContext) => AppBottomSheet(\n    title: 'Filter products',\n    child: const AppText(text: 'Sheet content'),\n  ),\n)",
      "AppBottomSheet.show<void>(\n  context: context,\n  builder: (sheetContext) => AppBottomSheet(\n    title: 'Lọc sản phẩm',\n    child: const AppText(text: 'Nội dung sheet'),\n  ),\n)",
    ),
    props: [
      _prop('child', 'Widget', '-', 'Main body content rendered inside the sheet.', 'Nội dung chính hiển thị bên trong sheet.', required: true),
      _prop('title', 'String', '-', 'Sheet title.', 'Tiêu đề của sheet.', required: true),
      _prop('description', 'String?', '-', 'Supporting text below the title.', 'Text mô tả nằm dưới tiêu đề.'),
      _prop('buttons', 'List<Widget>?', '-', 'Custom footer buttons, bypassing the default action builder.', 'Danh sách button footer tùy biến, bỏ qua action builder mặc định.'),
      _prop('size', 'AppBottomSheetSize?', 'medium', 'Controls padding, max height, and action size.', 'Điều khiển padding, max height và kích thước action.'),
      _prop('actionOrientation', 'AppBottomSheetActionOrientation?', 'vertical', 'Stacks footer actions vertically or horizontally.', 'Xếp footer action theo chiều dọc hoặc ngang.'),
      _prop('showDragHandle', 'bool?', 'true', 'Shows the drag handle above the title.', 'Hiển thị drag handle phía trên tiêu đề.'),
      _prop('showCloseIcon', 'bool?', 'true', 'Shows the floating close icon button.', 'Hiển thị nút icon đóng nổi.'),
      _prop('useSafeArea', 'bool?', 'true', 'Wraps the sheet in SafeArea on supported edges.', 'Bọc sheet bằng SafeArea ở các cạnh phù hợp.'),
      _prop('backgroundColor', 'Color?', 'ColorTokens.bgElevated', 'Background color of the sheet container.', 'Màu nền của container sheet.'),
      _prop('topBorderRadius', 'BorderRadiusGeometry?', 'RadiusTokens.radiusL', 'Top border radius of the sheet.', 'Bo góc trên của sheet.'),
      _prop('titleTextSize', 'AppTextSize?', 'size default', 'Typography token for the title.', 'Token typography cho tiêu đề.'),
      _prop('titleColor', 'Color?', 'ColorTokens.textDefault', 'Explicit title color override.', 'Ghi đè màu tiêu đề.'),
      _prop('titleStyle', 'TextStyle?', '-', 'Custom title text style.', 'Text style tùy biến cho tiêu đề.'),
      _prop('titleTextAlign', 'TextAlign?', 'center', 'Alignment of the title text.', 'Căn lề của text tiêu đề.'),
      _prop('descriptionColor', 'Color?', 'ColorTokens.textDescription', 'Explicit description color override.', 'Ghi đè màu của mô tả.'),
      _prop('descriptionStyle', 'TextStyle?', '-', 'Custom description text style.', 'Text style tùy biến cho mô tả.'),
      _prop('dragHandleColor', 'Color?', 'ColorTokens.borderDefault', 'Color of the drag handle.', 'Màu của drag handle.'),
      _prop('dragHandleWidth', 'double?', 'size default', 'Custom drag handle width.', 'Chiều rộng tùy biến của drag handle.'),
      _prop('dragHandleHeight', 'double?', 'size default', 'Custom drag handle height.', 'Chiều cao tùy biến của drag handle.'),
      _prop('dragHandleBottomGap', 'double?', 'size default', 'Gap below the drag handle.', 'Khoảng cách phía dưới drag handle.'),
      _prop('closeIcon', 'Widget?', 'Icons.close', 'Custom close icon widget.', 'Widget icon đóng tùy biến.'),
      _prop('closeIconColor', 'Color?', 'ColorTokens.iconDefault', 'Color of the close icon.', 'Màu của icon đóng.'),
      _prop('closeIconSize', 'double?', 'size default', 'Size of the close icon.', 'Kích thước của icon đóng.'),
      _prop('closeButtonSize', 'double?', 'size default', 'Hit target size of the close button.', 'Kích thước vùng bấm của nút đóng.'),
      _prop('closeButtonTopOffset', 'double?', 'derived from close size', 'Vertical offset of the floating close button.', 'Offset dọc của nút đóng nổi.'),
      _prop('closeButtonRightOffset', 'double?', 'derived from close size', 'Horizontal offset of the floating close button.', 'Offset ngang của nút đóng nổi.'),
      _prop('onClose', 'VoidCallback?', 'Navigator.maybePop', 'Callback when the close button is tapped.', 'Callback khi nhấn nút đóng.'),
      _prop('actionButtonSize', 'AppButtonSize?', 'size default', 'Button size used by generated footer actions.', 'Kích thước button dùng cho footer action được tạo mặc định.'),
      _prop('actionSpacing', 'double?', 'size default', 'Gap between footer actions.', 'Khoảng cách giữa các footer action.'),
      _prop('actionTextStyle', 'TextStyle?', '-', 'Text style merged into generated footer buttons.', 'Text style được merge vào các footer button mặc định.'),
      _prop('primaryActionTextColor', 'Color?', '-', 'Text color override for the generated primary action.', 'Ghi đè màu text cho primary action mặc định.'),
      _prop('secondaryActionTextColor', 'Color?', '-', 'Text color override for the generated secondary action.', 'Ghi đè màu text cho secondary action mặc định.'),
      _prop('cancelActionTextColor', 'Color?', '-', 'Text color override for the generated cancel action.', 'Ghi đè màu text cho cancel action mặc định.'),
      _prop('primaryActionVariant', 'AppButtonVariant?', 'AppButtonVariant.primary', 'Variant of the generated primary action.', 'Variant của primary action mặc định.'),
      _prop('secondaryActionVariant', 'AppButtonVariant?', 'AppButtonVariant.outline', 'Variant of the generated secondary action.', 'Variant của secondary action mặc định.'),
      _prop('cancelActionVariant', 'AppButtonVariant?', 'AppButtonVariant.fallback', 'Variant of the generated cancel action.', 'Variant của cancel action mặc định.'),
      _prop('titlePrimaryAction', 'String?', '-', 'Label of the generated primary action.', 'Nhãn của primary action mặc định.'),
      _prop('onPrimaryAction', 'VoidCallback?', '-', 'Callback for the generated primary action.', 'Callback của primary action mặc định.'),
      _prop('titleSecondaryAction', 'String?', '-', 'Label of the generated secondary action.', 'Nhãn của secondary action mặc định.'),
      _prop('onSecondaryAction', 'VoidCallback?', '-', 'Callback for the generated secondary action.', 'Callback của secondary action mặc định.'),
      _prop('titleCancelAction', 'String?', '-', 'Label of the generated cancel action.', 'Nhãn của cancel action mặc định.'),
      _prop('onCancelAction', 'VoidCallback?', '-', 'Callback for the generated cancel action.', 'Callback của cancel action mặc định.'),
    ],
    examples: buildBottomSheetExamples(),
  ),
  'app-modal': WidgetDocEntry(
    slug: 'app-modal',
    widgetName: 'AppModal',
    title: _t('AppModal', 'AppModal'),
    summary: _t(
      'Use AppModal for focused confirmation, decision, and approval flows that temporarily pause the rest of the interface.',
      'Dùng AppModal cho flow xác nhận, quyết định và phê duyệt có trọng tâm, tạm dừng phần còn lại của giao diện.',
    ),
    quickStart: _t(
      "AppModal.show<bool>(\n  context: context,\n  builder: (dialogContext) => AppModal(\n    title: 'Delete item?',\n    child: const SizedBox.shrink(),\n  ),\n)",
      "AppModal.show<bool>(\n  context: context,\n  builder: (dialogContext) => AppModal(\n    title: 'Xóa mục này?',\n    child: const SizedBox.shrink(),\n  ),\n)",
    ),
    props: [
      _prop('child', 'Widget', '-', 'Body content rendered inside the modal.', 'Nội dung body hiển thị bên trong modal.', required: true),
      _prop('title', 'String', '-', 'Modal title.', 'Tiêu đề của modal.', required: true),
      _prop('description', 'String?', '-', 'Supporting message below the title.', 'Thông điệp mô tả bên dưới tiêu đề.'),
      _prop('headerIcon', 'Widget?', 'type default', 'Custom header icon override.', 'Ghi đè icon phần header.'),
      _prop('buttons', 'List<Widget>?', '-', 'Custom footer button list.', 'Danh sách button footer tùy biến.'),
      _prop('modalType', 'AppModalType', 'normal', 'Visual type such as normal, info, warning, danger, or success.', 'Kiểu hiển thị như normal, info, warning, danger hoặc success.'),
      _prop('size', 'AppModalSize', 'small', 'Controls modal width and spacing.', 'Điều khiển chiều rộng và spacing của modal.'),
      _prop('showCloseIcon', 'bool', 'true', 'Shows the close icon button.', 'Hiển thị nút icon đóng.'),
      _prop('closeIconColor', 'Color?', 'type default', 'Explicit close icon color override.', 'Ghi đè màu icon đóng.'),
      _prop('onClose', 'VoidCallback?', '-', 'Callback for the close icon action.', 'Callback cho hành động icon đóng.'),
      _prop('titleBackAction', 'String?', '-', 'Label of the back action button.', 'Nhãn của nút back action.'),
      _prop('onBackAction', 'VoidCallback?', '-', 'Callback for the back action button.', 'Callback của nút back action.'),
      _prop('titlePrimaryAction', 'String?', '-', 'Label of the primary action button.', 'Nhãn của nút primary action.'),
      _prop('onPrimaryAction', 'VoidCallback?', '-', 'Callback for the primary action button.', 'Callback của nút primary action.'),
      _prop('titleSecondaryAction', 'String?', '-', 'Label of the secondary action button.', 'Nhãn của nút secondary action.'),
      _prop('onSecondaryAction', 'VoidCallback?', '-', 'Callback for the secondary action button.', 'Callback của nút secondary action.'),
      _prop('titleCancelAction', 'String?', '-', 'Label of the cancel action button.', 'Nhãn của nút cancel action.'),
      _prop('onCancelAction', 'VoidCallback?', '-', 'Callback for the cancel action button.', 'Callback của nút cancel action.'),
    ],
    examples: buildModalExamples(),
  ),
};

List<String> get documentedWidgetNames =>
    widgetDocsBySlug.values.map((entry) => entry.widgetName).toList()..sort();
